name: 📚 Documentation Issue
description: Report an issue with documentation
title: "[DOCS] "
labels: ["documentation", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: input
    id: page
    attributes:
      label: Documentation Page
      description: Which documentation page has the issue?
      placeholder: e.g., README.md, modules/azure-openai/README.md
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of documentation issue is this?
      options:
        - Incorrect information
        - Missing information
        - Unclear/confusing content
        - Broken link
        - Formatting issue
        - Spelling/grammar error
        - Example doesn't work
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the documentation issue
      placeholder: What's wrong with the documentation?
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How would you improve this documentation?
      placeholder: What should the documentation say instead?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the documentation issue
      placeholder: Any additional information that might be helpful
